name: santa
description: Santa Challenge

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: 12.1.0
  flutter_svg: 2.0.9
  intl: 0.18.1
  freezed: 2.4.5
  freezed_annotation: 2.4.1
  flutter_bloc: 8.1.3
  url_launcher: 6.2.1
  dio: 5.3.4
  injectable: 2.3.2
  get_it: 7.6.4
  cupertino_icons: ^1.0.2
  json_serializable:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
  build_runner: 2.4.6
  injectable_generator: 2.4.1
  mocktail: ^1.0.1
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/logo/
    - assets/images/
    - assets/json/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/ubuntu-regular.ttf
        - asset: assets/fonts/ubuntu/ubuntu-medium.ttf
          weight: 500
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/roboto-regular.ttf
